### ISSUE TITLE
function write_sol creates incorrect soil file

### ISSUE THREAD

**Issue by maria-quade** [palderman/DSSAT#48]
Dear Mr Palderman,

When using the write_sol function, R gives a large number of warnings.
The resulting sol file looks fine, but there are some problems 
First line:
![grafik](https://github.com/palderman/DSSAT/assets/135954927/ec4b9296-5d22-4243-8922-1f2d64b1d67a)

![grafik](https://github.com/palderman/DSSAT/assets/135954927/4fd782a0-2363-4f83-b689-f97cf0920ba6)

Is it possible to solve this problem?
I need to prepare a large number of soil files, having this fixed in the R package would be very convenient.

Thank you very much! Maria

**Comment by palderman** [comment]
Hi @maria-quade,

Sorry for the delayed response. Let me check into this and get back to you shortly.

**Comment by palderman** [comment]
I am having difficulty reproducing your specific problem. Would you be able to share a reproducible example (see [https://en.wikipedia.org/wiki/Minimal_reproducible_example](https://en.wikipedia.org/wiki/Minimal_reproducible_example).

Also, I don't know if it's directly relevant to the problem at hand, but I notice that your soil ID only has 9 digits. I think DSSAT-CSM expects this to be 10 digits.

**Comment by maria-quade** [comment]
Dear Mr Palderman,

Thank you for looking into this. 
When I load a default soil file as a dummy and save this soil file again under a different name, the length of the soil ID is reduced to 9 digits. 

soil <- read_sol("C:/DSSAT48/Soil/BR.sol")
write_sol(soil,file_name="JK.SOL",append=F)

I receive the following warning messages:
Warning messages:
1: In .f(.l[[1L]][[i]], .l[[2L]][[i]], .l[[3L]][[i]], ...) :
  Column PEDON values were trimmed to fit specified column width. Please check output for introduced errors.
2: In .f(.l[[1L]][[i]], .l[[2L]][[i]], .l[[3L]][[i]], ...) :
  Column PEDON values were trimmed to fit specified column width. Please check output for introduced errors.
3: In .f(.l[[1L]][[i]], .l[[2L]][[i]], .l[[3L]][[i]], ...) :
  Column PEDON values were trimmed to fit specified column width. Please check output for introduced errors

Thanks for checking!

Best, Maria

**Comment by palderman** [comment]
Ah! I think this might be related to a bug that has been fixed in the current development branch. Would you please check whether or not that version solves your problem?

You can install the develop branch from the repository with:

```
devtools::install_github("palderman/DSSAT", ref = "develop")
```

or

```
remotes::install_github("palderman/DSSAT", ref = "develop")
```

**Comment by maria-quade** [comment]
Dear Mr Palderman,
Thank you so much!
This solves some of my problems. However, the space before the location is still missing. But I solved this by adding this to my script.

**Comment by palderman** [comment]
Glad you were able to figure out a work-around. I just pushed a commit that changes the format for the `SITE` variable. I think it should work now. Would you mind reinstalling the `develop` branch as before and checking to see if the change I made has the intended output for you?

**Comment by maria-quade** [comment]
Thank you for your efforts! The soil file looks good now, everything is in its place.
